### ISSUE TITLE
Create locks.api

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#228]
* Provide a resource "/mutex/{name}" that implements mutex semantics.
  * Any participant attempting to LOCK it are placed in queue. The owner can UNLOCK
  * Participants are removed from the queue when they disconnect.  If the owner disconnects, it's a disconnect.
  * Open question:  should the "OK" response signify acquisition of the lock?  This would seem to make the client code cleaner and read more naturally.  Is it consistent with the rest of the API?  Is there value in receiving an "OK" for successful registration?  Should successful registration and state changes on the mutex go to the callback function?
* This is the only API that will use internal leadership election from now on.  All other APIs will use the 
lock.api.
  * Leadership will be implemented as ownership of the mutex.

**Comment by Kevin-K** [comment]
implemented in PR #278

>* Open question: should the "OK" response signify acquisition of the lock? This would seem to make the client code cleaner and read more naturally. Is it consistent with the rest of the API? 

"ok" signifies acquisition of the lock. 

>Is there value in receiving an "OK" for successful registration? Should successful registration and state changes on the mutex go to the callback function?

A `lock` action should act like a `get`, it is a 1 time desired result and the client code will wait until it can obtain it. Using a callback for the `onLock` could lead to confusion that an individual `lock` could be triggered multiple times. Rather, since lock responds like `get`, it will resolve a promise once and then remove its registration.
