### ISSUE TITLE
Create an AjaxPersistenceQueue to throttle and de-duplicate API persistence to the server.

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#239]
Create an AjaxPersistenceQueue class to handle the logic of persisting API resources back to the server with the following constraints:
* A maximum number of in-flight connections to the server at any given time (default: 4).
* A resource can only be in the queue once.
  * If a resource is queued while it's waiting for the connection pool, simply update the entry.
  * If a resource is queued while it's save is in flight, queue it to save *after* the current request completes.
* PUT and DELETE to the node's `self` URL to create, update, or delete it.

Interface:
Constructor: `ozpIwc.AjaxPersistenceQueue(config)`
* Param {integer} [config.poolSize=4] - how many connections to allow at one time.

`AjaxPersistenceQueue.prototype.queueNode(iwcUri,node)`
* Param: {string} iwcUri - the iwcUri, minus protocol (e.g. "data.api/foo/bar", "system.api/application/12345")
* Param {ApiNode} node - the ApiNode to be queued for save
* Returns {Promise} - a promise that resolves when the resource has been successfully saved

**Comment by Kevin-K** [comment]
Due to Ozone Platform backend complications, default number of in-flight connections changed from [4 to 1](https://github.com/ozone-development/ozp-iwc/blob/53258cb7b2018639dc1bbb481c59426270f8b49e/app/js/bus/util/ajaxPersistenceQueue.js#L10).

This is easily changed for other backend implementations/Ozone Platform backend enhancements. 
When [instantiating an API in the defaultWiring.js](https://github.com/ozone-development/ozp-iwc/blob/53258cb7b2018639dc1bbb481c59426270f8b49e/app/js/defaultWiring.js#L71) add a custom `persistenceQueue` to its config.
```
 ozpIwc.dataApi = new ozpIwc.DataApi({
    'name': "data.api",
    'poolSize': 4
});
```

**Comment by Kevin-K** [comment]
AjaxPersistenceQueue has been merged in, follow up issues should be opened pertaining to a change in the default poolSize.
