### ISSUE TITLE
[Question] IWC + Backend Errors

### ISSUE THREAD

**Issue by emosher** [ozone-development/ozp-iwc#267]
I cloned the IWC repo and I have a local setup running the IWC bus with [nano-server](https://www.npmjs.com/package/nano-server).  When I run my app, I include the IWC and connect to my local bus.

```javascript
var client = new iwcClient.Client({
  peerUrl: "http://localhost:3001"
});
```

I can see with the debugger that I am able to send/receive things via the IWC, but I receive console errors because the IWC is trying to connect to a backend that is not there.  I understand that IWC uses the backend to persist things, but as of right now I have no need to do this.  It would be perfectly reasonable in my case to use only IWC and persist the things I need with the backend I am writing.  With the new design of OZP, I would *think* that this would be reasonable.

The code I was toying around with looks something like this:

```javascript
client.connect().then(function(){
  var dataApi = client.data();
  
  // I'm using AngularJS, so $scope.dashboardItems is what I'm sending to the IWC
  $scope.dashboardItems.forEach(function(item) {
    dataApi.addChild('/dashboard', { entity: item });
  });
}).then(function(){
  var dataApi = client.data();
  dataApi.list('/dashboard').then(function(res){
    console.log(res.entity);
  });
}).catch(function(err) {
  console.log('This is never called');
  console.error(err);
});
```

Questions on this:
 * Is there an option to disable the backend connection? Maybe by a `persist: false` option when setting up the client connection?
 * Is there a way to silence the errors?  In my code above the catch clause is never called

I've dug through the docs and the code and have not yet found an answer/workaround.  I'm including the console errors below.

![iwc-ajax](https://cloud.githubusercontent.com/assets/1850338/7638116/9bb5fb50-fa40-11e4-908d-f2ec39842b86.png)

**Comment by Kevin-K** [comment]
### Info
Just to get a little more information, 3/4 core api's have backend connections:
**Data.api**: for key-value persistence (both loading/unloading state)
**System.api**: for application registration knowledge (loading app listings from backend)
**Intents.api**: for static intent handler definitions (loading handler definitions, ie: application/json/view, its icon/label/(todo: persisted handler preferences)

Disabling backend connections for the three will still produce a functional bus, the loss of system.api backend will remove app awareness though, so you will be limited to only performing to handling intents with currently open applications rather than having the IWC prompt to load an application who's listing was gathered via the system.api.

With that in mind, you can still utilize the data.api  without a backend connection with the loss of loading saved state & persisting current state.

The errors you're getting happen at the initialization of the bus because the API's are sending off a request to grab data from their backends, but the IWC will continue functioning, just with lack of loaded data if no response is received.


### Thoughts
Here's my thoughts on the matter, we'll flow these into development taskings should seem fit.

 *  From a performance perspective I agree that you should be able to disable communications if desired, why have the bus fire AJAX calls if you know your deployment is set up such responses wont be received?
    * It will be investigated should a config param be placed on the `defaultWiring.js` to allow  deployments to disable backend communication. This would allow you to disable comms from the `iframe_peer.html` where deployment customization takes place.
    * Should control be added to only disable persistence? If a backend supplies some initial state for a user but won't accept any persistence of state, should a configuration be put in place to block data.api persistence for a deployment? Does this dig into an issue of giving too much customization that can lead to deployment difficulties? 

* The uncaught errors should be caught and passed through the IWC logging utility `ozpIwc.log` at respectable logging level with more useful notification (logging level will drive silencing).

**Comment by cgross** [comment]
FWIW, we're in the same boat as @emosher.  We want the power of the bus but would rather not have any backend requirements.  

cc @danhooper, @jziggas

**Comment by Kevin-K** [comment]
Using the bus without a backend is possible, but you will still be dependent on a domain hosting the IWC so that the browser can use local storage on that common domain. So long as that requirement can be met (you can host the IWC libraries statically, the `ozpIwc.Client({peerUrl: <...>})` just has to point to the dir path  library ( ex) www.myApp.com/iwc if iframe_peer is www.myApp.com/iwc/iframe_peer.html)

We recently added a simple express+NeDB Node.js backend bundled with IWC for example purposes of data.api persistence use & system.api application listings.  

If no use of data persistence or application listing is of interest, I'll throw together another deployable backend that you can just fire up with `grunt serve-no-backends`

**Comment by Kevin-K** [comment]
Finally had spare time to address the no backend configuration. I'm reworking deployment configurations for the IWC so that all you have to do is alter a `ozpIwc.conf.js` that will be served along side the `ozpIwc-bus.js` to enable/disable backend communications among other common configurations.

#325 will be updating configuration work status on that issue, currently testing/documenting. Expect some update on this after the long weekend, will be bumping to version `1.1.0` with this change.

**Comment by Kevin-K** [comment]
documentation on the "no-backend" setup is [here](http://ozone-development.github.io/ozp-iwc/getting_started/bus_configuration/overview.html)

Tagging 1.1.0 and closing issue, set your `ozpIwc.conf.js` file to either not include `ozpIwc.config.backendSupport` or set it to false (it is false by default)

Feel free to follow up with futher requests via issues for more config properties.
