### ISSUE TITLE
Using window.top as a bus?

### ISSUE THREAD

**Issue by speigg** [ozone-development/ozp-iwc#328]
I was testing ozp-iwc and there seems to be a lot of latency with the localstorage bus. Would it be possible to use an in-memory bus living at `window.top` if all widgets were loaded in iframes in the same window (ideally using the MessageChannel api to communicate between frames)?

**Comment by Kevin-K** [comment]
The concept behind using localstorage does come with some latency, two contributing factors:
  1. Every widget is running an instance of the bus (either leading or dormant based    on the consensus algorithms) and every instance of the bus sees every write to the transport link (localStorage) and chooses to pick up packets off the link as needed for its client(s). This adds complexity when using the local storage event because now every event handler see's every event even if its not needed by the client's that connect to it. 
  2. Data transmissions occur in a FIFO order by using `setImmediate` to push transmits on the end of the current event loop, a practice that I want to revisit and see if can be done without. Browser polyfills use `setTimeout(fn,0)` to implement setImmediate which opens the issue of non-visible pages governing setTimeouts/setIntervals to [a minimum 1 second](http://blog.pivotal.io/labs/labs/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs).

My main concern with implementing a `window.top` link is that I'm uncertain from a framework perspective what limitations that brings, primarily CORS related. 

**My quick test**

1. I put an IWC widget in the domain: `www.myapp.com` with a bus domain of: `www.mybus.com`.

2. The Iframe is loaded into a parent page that matches the IWC bus and could run an instance of the IWC bus on it: `www.mybus.com`.

3. The widget's instance of the IWC bus cannot communicate with the parent window even though they are of the same domain (`www.mybus.com`) because to reach window.top, it must pass through the window of `www.myapp.com` 

**ex:** `www.mybus.com`(instance in iframe widget) ---> `www.myapp.com`(iframed widget) ---> `www.mybus.com` (page holding the iframes).

Trying to access `window.top` from inside the iwc instance in the iframe throws a `DOMException` because it is crossing domains to get to the top. Including widgets in the same domain(ie: move myapp to mybus) as the bus alleviates the CORS issue, but cuts into the purpose of the IWC of bringing collaborative use of widgets together. 

Currently I'm investigating the use of shared webworkers, which should eliminate point 1 about localstorage above for Chrome/Firefox (#330) and drop the need for using localstorage all together, but for older browsers the current implementation would still be used.

**Comment by speigg** [comment]
If the bus is running in the top window, why are three layers of communication needed here? The bus running at window.top and send and receive messages to/from the iframed widget.

**Comment by speigg** [comment]
A shared worker sounds like it would be ideal, it's too bad the browser support is so terrible though

**Comment by speigg** [comment]
@Kevin-K You should be able to access window.postMessage regardless of domains. `window.postMessage` is not governed by same-origin policy, so `window.top.postMessage` should work (even if `window.top` by itself gives you errors in the console)

If I understand the source correctly, it seems that the PostMessageListener would allow for child frames to register as participants in the bus running at window.top (without requiring multiple instances of the bus to run for each child frame). Each iframe would need to establish a connection using a window.top as it's peer (I think this is the only unimplemented part, correct?).

**Comment by Kevin-K** [comment]
Somehow missed your message last week.

Interesting I didn't realize window.top.postMessage would work. Do you know what the browser support for it is/is it pollyfill-able? 

I had played with the idea of `window.opener` on popup windows (IWC Intent chooser) but you run the issue of the bus leader closing during the popup window's lifespan and breaking its functionality (because it tied directly via window.opener.postMessage). 

That said for all connections in a single window chain routing over postmessage should deliver "locally" **if** that window chain's bus is the leader (if it isn't the message has to go out over localstorage for the bus leader to handle it). 

In your case of all iframes in one page there would be only one bus, but if another application was opened in another browser tab it needs to be able to connect to the same bus. 

If the other tab was opened first then your case of 1 page multi-iframes opened second, the other tab would take leadership and the multi-iframe would while sharing a bus on window.top still have to use localstorage to an extent. Although, thats just given current functionality, the consensus algorithms could be modified to grant higher priority to an instance containing multiple postMessage participants.

The postMessageListener is intended for what you mentioned, I'll take a dig through and see about the unimplemented part. There's a config flag for it as well in ozpIwc.conf.js [(not in gitbook docs)](https://github.com/ozone-development/ozp-iwc/blob/master/app/js/bus/wiring/configLoading.js#L134)

Thanks for bringing up this info, I've been working deep on other aspects that I've lost touch with the transport layer

**Comment by speigg** [comment]
I didn't know about `window.opener`! I wonder if `window.opener.opener.opener` (etc) is required to reach the original opener, in the case of chained calls to `window.open`. Might be crazier if iframes are in the mix, and they can open windows too. May have to do something silly like call `window.opener` and `opener.top` recursively until it resolves (but this is of course an extreme scenario). I suppose if the bus leader tries to close when the popup window is still open, the bus leader can prompt the user or close the popup windows first, or close them itself?  Also, apparently `window.opener` is not available if the opened window is not the same domain is the opener. 

For my case, I only need the applications in one top-level page. I don't understand the role of the leader though, is there any documentation on it?

Regarding browser support for `window.top.postMessage`, it should be supported in virtually all modern browsers, no polyfills needed (I've used/tested it on chrome/safari/firefox, though there seems to be some bugs with postMessage accross tabs/windows in IE, using window.opener I guess):
http://caniuse.com/#feat=x-doc-messaging

**Comment by Kevin-K** [comment]
>For my case, I only need the applications in one top-level page (with the applications all being loaded from different domains). I don't understand the role of the leader though, is there any documentation on it?

Currently working on a rework of the gitbook documents, going to cover it on a surface level in there. Essentially since every instance of a client run's a bus. A distributed consensus algorithm has to be used to figure out which bus instance is the "Leader" and handles all the IWC client requests. Additionally bus "state" has to be passed on to a new Leader should the current one close.

**Comment by Kevin-K** [comment]
Cleaning up github issues, tagging this for #199 (and other browsers) as an investigation point for future transport methods.

Thanks for the info on `window.top` @speigg . I'll be sure to tag this issue should window.top be used in the transport layer.
